export type RentoraApiQueryClientKey =
  | 'me'
  | 'apartmentList'
  | 'apartmentDetail'
  | 'tenantList'
  | 'tenantDetail'
  | 'maintenanceList'
  | 'maintenanceDetail'
export type RentoraApiExecuteClientKey =
  | 'authenticate'
  | 'createApartment'
  | 'putPresignedUrl'
  | 'setupApartment'
  | 'firstTimePasswordReset'
  | 'createMaintenance'
  | 'updateMaintenance'
  | 'deleteMaintenance'
  | 'createTenant'
  | 'updateTenant'
  | 'updateTenantPassword'
