export type RentoraApiQueryClientKey =
  | 'me'
  | 'apartmentList'
  | 'apartmentDetail'
  | 'invoiceList'
  | 'invoiceDetail'
  | 'tenantList'
  | 'tenantDetail'
export type RentoraApiExecuteClientKey =
  | 'authenticate'
  | 'createApartment'
  | 'putPresignedUrl'
  | 'setupApartment'
  | 'firstTimePasswordReset'
  | 'createTenant'
  | 'updateTenant'
  | 'updateTenantPassword'
